-- Generated by agent-3 (Database)
-- Task: Music Player Interface

-- Set up database structure for Music Player Interface
CREATE TABLE IF NOT EXISTS newmigration (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);