-- Generated by agent-3 (Database)
-- Task: Webflow Integration Guides

-- Set up database structure for Webflow Integration Guides
CREATE TABLE IF NOT EXISTS newmigration (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);