-- Generated by agent-3 (Database)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
-- Task: News Ticker Webflow

-- Set up database structure for News Ticker Webflow
=======
-- Task: Video Widget Webflow

-- Set up database structure for Video Widget Webflow
>>>>>>> task/1752797361817-video-widget-webflow
=======
-- Task: Music Player Interface

-- Set up database structure for Music Player Interface
>>>>>>> task/1752797361980-music-player-interface
=======
-- Task: Widget Documentation

-- Set up database structure for Widget Documentation
>>>>>>> task/1752797362020-widget-documentation
CREATE TABLE IF NOT EXISTS newmigration (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);